# Pandas basic

In [4]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\adnan\appdata\roaming\python\python312\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\adnan\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\adnan\appdata\roaming\python\python312\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\adnan\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 180.4 kB/s eta 0:00:52
   -- ------------------------------------- 0.5/9.8 MB 180.4 kB/s eta 0:00:52
   -- ------------------------------------- 0.5/9.8 MB 180.4 kB/s eta 0:00:52
   -- ------------------------------------- 0.5/9.8 MB 180.4 kB/s eta 0:00:52
   -- ------------------------------------- 0.5/9.8 MB 180.4 kB/s eta 0:00:52
   -- ------------------------------------- 0.5/9.8 MB 180.4 kB/s eta 0:00:52
   --- ------------------------------------ 0.8/9.8 MB 188.5 kB/s eta 0:00:48
   --- ------------------------------------ 0.8/9.8 MB 188.5 kB/s eta 0:00:48
   --- ------------------------------------ 0.8/9.8 MB 188.5 kB/s eta 0:00:48
   --- ------------------------------------ 0.8/9.8 MB 188.5 kB/s eta 0:00:48
   ---- ----------------------------------- 1.0/9.8 MB 219.8 kB/s eta 0:00:40
   ---- ----------------------------------- 1.0/9.8 MB 219.8 kB/s eta 0:00:40
   ---- ----------------------------------- 1.0/9.8 MB 219.8 kB/s eta 0:00:40
   ---- ----------------------------------- 1.0/9.8 MB 219.8 kB/s eta 0:00:40
   ---- ----------------------------------- 1.0/9.8 MB 219.8 kB/s eta 0:00:40
   ---- ----------------------------------- 1.0/9.8 MB 219.8 kB/s eta 0:00:40
   ----- ---------------------------------- 1.3/9.8 MB 225.9 kB/s eta 0:00:38
   ----- ---------------------------------- 1.3/9.8 MB 225.9 kB/s eta 0:00:38
   ----- ---------------------------------- 1.3/9.8 MB 225.9 kB/s eta 0:00:38
   ----- ---------------------------------- 1.3/9.8 MB 225.9 kB/s eta 0:00:38
   ----- ---------------------------------- 1.3/9.8 MB 225.9 kB/s eta 0:00:38
   ------ --------------------------------- 1.6/9.8 MB 229.8 kB/s eta 0:00:36
   ------ --------------------------------- 1.6/9.8 MB 229.8 kB/s eta 0:00:36
   ------ --------------------------------- 1.6/9.8 MB 229.8 kB/s eta 0:00:36
   ------- -------------------------------- 1.8/9.8 MB 249.1 kB/s eta 0:00:32
   ------- -------------------------------- 1.8/9.8 MB 249.1 kB/s eta 0:00:32
   ------- -------------------------------- 1.8/9.8 MB 249.1 kB/s eta 0:00:32
   ------- -------------------------------- 1.8/9.8 MB 249.1 kB/s eta 0:00:32
   ------- -------------------------------- 1.8/9.8 MB 249.1 kB/s eta 0:00:32
   ------- -------------------------------- 1.8/9.8 MB 249.1 kB/s eta 0:00:32
   ------- -------------------------------- 1.8/9.8 MB 249.1 kB/s eta 0:00:32
   ------- -------------------------------- 1.8/9.8 MB 249.1 kB/s eta 0:00:32
   -------- ------------------------------- 2.1/9.8 MB 226.7 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.7 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.7 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.7 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.7 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.7 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.7 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.7 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.7 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.7 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.7 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.7 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.7 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.7 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.7 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.7 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.7 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.7 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.7 kB/s eta 0:00:34
   -------- ------------------------------- 2.1/9.8 MB 226.7 kB/s eta 0:00:34
   --------- ------------------------------ 2.4/9.8 MB 174.5 kB/s eta 0:00:43
   --------- ------------------------------ 2.4/9.8 MB 174.5 kB/s eta 0:00:43
   --------- ------------------------------ 2.4/9.8 MB 174.5 kB/s eta 0:00:43
   --------- ------------------------------ 2.4/9.8 MB 174.5 kB/s eta 0:00:43
   --------- ------------------------------ 2.4/9.8 MB 174.5 kB/s eta 0:00:43
   --------- ------------------------------ 2.4/9.8 MB 174.5 kB/s eta 0:00:43
   --------- ------------------------------ 2.4/9.8 MB 174.5 kB/s eta 0:00:43
   --------- ------------------------------ 2.4/9.8 MB 174.5 kB/s eta 0:00:43
   --------- ------------------------------ 2.4/9.8 MB 174.5 kB/s eta 0:00:43
   --------- ------------------------------ 2.4/9.8 MB 174.5 kB/s eta 0:00:43
   --------- ------------------------------ 2.4/9.8 MB 174.5 kB/s eta 0:00:43
   --------- ------------------------------ 2.4/9.8 MB 174.5 kB/s eta 0:00:43
   ---------- ----------------------------- 2.6/9.8 MB 162.0 kB/s eta 0:00:45
   ---------- ----------------------------- 2.6/9.8 MB 162.0 kB/s eta 0:00:45
   ---------- ----------------------------- 2.6/9.8 MB 162.0 kB/s eta 0:00:45
   ---------- ----------------------------- 2.6/9.8 MB 162.0 kB/s eta 0:00:45
   ---------- ----------------------------- 2.6/9.8 MB 162.0 kB/s eta 0:00:45
   ---------- ----------------------------- 2.6/9.8 MB 162.0 kB/s eta 0:00:45
   ---------- ----------------------------- 2.6/9.8 MB 162.0 kB/s eta 0:00:45
   ---------- ----------------------------- 2.6/9.8 MB 162.0 kB/s eta 0:00:45
   ---------- ----------------------------- 2.6/9.8 MB 162.0 kB/s eta 0:00:45
   ---------- ----------------------------- 2.6/9.8 MB 162.0 kB/s eta 0:00:45
   ---------- ----------------------------- 2.6/9.8 MB 162.0 kB/s eta 0:00:45
   ---------- ----------------------------- 2.6/9.8 MB 162.0 kB/s eta 0:00:45
   ---------- ----------------------------- 2.6/9.8 MB 162.0 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ----------- ---------------------------- 2.9/9.8 MB 153.1 kB/s eta 0:00:45
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------ --------------------------- 3.1/9.8 MB 105.6 kB/s eta 0:01:03
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   ------------- -------------------------- 3.4/9.8 MB 39.8 kB/s eta 0:02:40
   --------------- ------------------------ 3.7/9.8 MB 35.6 kB/s eta 0:02:52
   --------------- ------------------------ 3.7/9.8 MB 35.6 kB/s eta 0:02:52
   --------------- ------------------------ 3.7/9.8 MB 35.6 kB/s eta 0:02:52
   --------------- ------------------------ 3.7/9.8 MB 35.6 kB/s eta 0:02:52
   --------------- ------------------------ 3.7/9.8 MB 35.6 kB/s eta 0:02:52
   --------------- ------------------------ 3.7/9.8 MB 35.6 kB/s eta 0:02:52
   --------------- ------------------------ 3.7/9.8 MB 35.6 kB/s eta 0:02:52
   --------------- ------------------------ 3.7/9.8 MB 35.6 kB/s eta 0:02:52
   --------------- ------------------------ 3.7/9.8 MB 35.6 kB/s eta 0:02:52
   --------------- ------------------------ 3.7/9.8 MB 35.6 kB/s eta 0:02:52
   --------------- ------------------------ 3.7/9.8 MB 35.6 kB/s eta 0:02:52
   --------------- ------------------------ 3.7/9.8 MB 35.6 kB/s eta 0:02:52
   --------------- ------------------------ 3.7/9.8 MB 35.6 kB/s eta 0:02:52
   --------------- ------------------------ 3.7/9.8 MB 35.6 kB/s eta 0:02:52
   --------------- ------------------------ 3.7/9.8 MB 35.6 kB/s eta 0:02:52
   --------------- ------------------------ 3.7/9.8 MB 35.6 kB/s eta 0:02:52
   --------------- ------------------------ 3.7/9.8 MB 35.6 kB/s eta 0:02:52
   --------------- ------------------------ 3.7/9.8 MB 35.6 kB/s eta 0:02:52
   ---------------- ----------------------- 3.9/9.8 MB 38.4 kB/s eta 0:02:32
   ---------------- ----------------------- 3.9/9.8 MB 38.4 kB/s eta 0:02:32
   ---------------- ----------------------- 3.9/9.8 MB 38.4 kB/s eta 0:02:32
   ---------------- ----------------------- 3.9/9.8 MB 38.4 kB/s eta 0:02:32

WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (3.9 MB/9.8 MB, attempt 1)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [80]:
import pandas as pd

In [81]:
print(pd.__version__)

3.0.3

### series

In [82]:
age=[25.,22.,5.,2.,24.]
series=pd.Series(age)
series

0    25.0
1    22.0
2     5.0
3     2.0
4    24.0
dtype: float64

In [83]:
series[1]

np.float64(22.0)

In [84]:
age=['afnan','saif','hello']
series=pd.Series(age)
series

0    afnan
1     saif
2    hello
dtype: str

In [85]:
age=[True,False,True]
series=pd.Series(age)
series

0     True
1    False
2     True
dtype: bool

In [86]:
print(series.loc[1])
series[1]

False

np.False_

In [87]:
age=[25,22,5,2,24]
series=pd.Series(age,index=['afnan','saif','hello','ammar','hamdan'])
series

afnan     25
saif      22
hello      5
ammar      2
hamdan    24
dtype: int64

In [88]:
print(series['saif'])

22

In [89]:
print(series.loc['saif'])

22

In [90]:
print(series.iloc[1])

22

In [91]:
age={
    'afnan':20,
    'saif':5,
    'ammar':23,
    'hamdan':22,
    'hamdaan':30,
    'idrees':40
}

In [92]:
series=pd.Series(age)

In [93]:
print(series)

afnan      20
saif        5
ammar      23
hamdan     22
hamdaan    30
idrees     40
dtype: int64

In [94]:
print(series[series<=20])

afnan    20
saif      5
dtype: int64

### Dataframe

In [95]:
student={
    'name':['afnan','saif','ammar','fawaz'],
    'age':[10,20,22,18],
    'cgpa':[9,8.4,8,10]
}
df=pd.DataFrame(student)

In [96]:
print(df)    #print dataframe
df

    name  age  cgpa
0  afnan   10   9.0
1   saif   20   8.4
2  ammar   22   8.0
3  fawaz   18  10.0

    name  age  cgpa
0  afnan   10   9.0
1   saif   20   8.4
2  ammar   22   8.0
3  fawaz   18  10.0

In [97]:
df=pd.DataFrame(student, index=['stu1','stu2','stu3','stu4'])  #index data in the table

In [98]:
print(df.loc["stu1"])   #accessing one data in table with its given index

name    afnan
age        10
cgpa      9.0
Name: stu1, dtype: object

In [99]:
print(df.iloc[0])   # accessing data with it original index value
print(df.iloc[1:5])  # accessing

name    afnan
age        10
cgpa      9.0
Name: stu1, dtype: object
       name  age  cgpa
stu2   saif   20   8.4
stu3  ammar   22   8.0
stu4  fawaz   18  10.0

In [100]:
df["dept"]=["CSE","AI&DS","IT","AI&ML"] #add col
df

       name  age  cgpa   dept
stu1  afnan   10   9.0    CSE
stu2   saif   20   8.4  AI&DS
stu3  ammar   22   8.0     IT
stu4  fawaz   18  10.0  AI&ML

In [101]:
#adding row
stu5=pd.DataFrame({
    'name':'ram',
    'age':10,
    'cgpa':9
}, index=["stu5"])    #inserting single data
df=pd.concat([df,stu5])
df

       name  age  cgpa   dept
stu1  afnan   10   9.0    CSE
stu2   saif   20   8.4  AI&DS
stu3  ammar   22   8.0     IT
stu4  fawaz   18  10.0  AI&ML
stu5    ram   10   9.0    NaN

In [102]:
student=pd.DataFrame({
    'name':['sham','kavin'],
    'age':[19,17],
    'cgpa':[9,8],
    'dept':['ECE','CSBS']
}, index=["stu6","stu7"])    #inserting multiple data
df=pd.concat([df,student])
df

       name  age  cgpa   dept
stu1  afnan   10   9.0    CSE
stu2   saif   20   8.4  AI&DS
stu3  ammar   22   8.0     IT
stu4  fawaz   18  10.0  AI&ML
stu5    ram   10   9.0    NaN
stu6   sham   19   9.0    ECE
stu7  kavin   17   8.0   CSBS

In [103]:
df=pd.read_csv('data.csv')   #import dataFrame as csv file
df

    ID     Name  Duration          Date  Pulse  Maxpulse  Calories
0    1    Alice        60  '2020/12/01'    110       130     409.1
1    2      Bob        60  '2020/12/02'    117       145     479.0
2    3  Charlie        60  '2020/12/03'    103       135     340.0
3    4    Diana        45  '2020/12/04'    109       175     282.4
4    5      Eve        45  '2020/12/05'    117       148     406.0
5    6    Frank        60  '2020/12/06'    102       127     300.0
6    7    Grace        60  '2020/12/07'    110       136     374.0
7    8    Henry       450  '2020/12/08'    104       134     253.3
8    9     Iris        30  '2020/12/09'    109       133     195.1
9   10     Jack        60  '2020/12/10'     98       124     269.0
10  11    Karen        60  '2020/12/11'    103       147     329.3
11  12      Leo        60  '2020/12/12'    100       120     250.7
12  13    Megan        60  '2020/12/12'    100       120     250.7
13  14   Nathan        60  '2020/12/13'    106       128     345.3
14  15   Olivia        60  '2020/12/14'    104       132     379.3
15  16     Paul        60  '2020/12/15'     98       123     275.0
16  17    Quinn        60  '2020/12/16'     98       120     215.2
17  18   Rachel        60  '2020/12/17'    100       120     300.0
18  19      Sam        45  '2020/12/18'     90       112       NaN
19  20     Tina        60  '2020/12/19'    103       123     323.0
20  21      Uma        45  '2020/12/20'     97       125     243.0
21  22   Victor        60  '2020/12/21'    108       131     364.2
22  23    Wendy        45           NaN    100       119     282.0
23  24   Xavier        60  '2020/12/23'    130       101     300.0
24  25     Yara        45  '2020/12/24'    105       132     246.0
25  26     Zara        60  '2020/12/25'    102       126     334.5
26  27    Alice        60      20201226    100       120     250.0
27  28      Bob        60  '2020/12/27'     92       118     241.0
28  29  Charlie        60  '2020/12/28'    103       132       NaN
29  30    Diana        60  '2020/12/29'    100       132     280.0
30  31      Eve        60  '2020/12/30'    102       129     380.3
31  32    Frank        60  '2020/12/31'     92       115     243.0

In [104]:
df.head()   # get the first five row

   ID     Name  Duration          Date  Pulse  Maxpulse  Calories
0   1    Alice        60  '2020/12/01'    110       130     409.1
1   2      Bob        60  '2020/12/02'    117       145     479.0
2   3  Charlie        60  '2020/12/03'    103       135     340.0
3   4    Diana        45  '2020/12/04'    109       175     282.4
4   5      Eve        45  '2020/12/05'    117       148     406.0

In [105]:
df.tail()  #to get last five row

    ID     Name  Duration          Date  Pulse  Maxpulse  Calories
27  28      Bob        60  '2020/12/27'     92       118     241.0
28  29  Charlie        60  '2020/12/28'    103       132       NaN
29  30    Diana        60  '2020/12/29'    100       132     280.0
30  31      Eve        60  '2020/12/30'    102       129     380.3
31  32    Frank        60  '2020/12/31'     92       115     243.0

In [106]:
print(df.to_string()) # print all data

    ID     Name  Duration          Date  Pulse  Maxpulse  Calories
0    1    Alice        60  '2020/12/01'    110       130     409.1
1    2      Bob        60  '2020/12/02'    117       145     479.0
2    3  Charlie        60  '2020/12/03'    103       135     340.0
3    4    Diana        45  '2020/12/04'    109       175     282.4
4    5      Eve        45  '2020/12/05'    117       148     406.0
5    6    Frank        60  '2020/12/06'    102       127     300.0
6    7    Grace        60  '2020/12/07'    110       136     374.0
7    8    Henry       450  '2020/12/08'    104       134     253.3
8    9     Iris        30  '2020/12/09'    109       133     195.1
9   10     Jack        60  '2020/12/10'     98       124     269.0
10  11    Karen        60  '2020/12/11'    103       147     329.3
11  12      Leo        60  '2020/12/12'    100       120     250.7
12  13    Megan        60  '2020/12/12'    100       120     250.7
13  14   Nathan        60  '2020/12/13'    106       128     345.3
14  15   Olivia        60  '2020/12/14'    104       132     379.3
15  16     Paul        60  '2020/12/15'     98       123     275.0
16  17    Quinn        60  '2020/12/16'     98       120     215.2
17  18   Rachel        60  '2020/12/17'    100       120     300.0
18  19      Sam        45  '2020/12/18'     90       112       NaN
19  20     Tina        60  '2020/12/19'    103       123     323.0
20  21      Uma        45  '2020/12/20'     97       125     243.0
21  22   Victor        60  '2020/12/21'    108       131     364.2
22  23    Wendy        45           NaN    100       119     282.0
23  24   Xavier        60  '2020/12/23'    130       101     300.0
24  25     Yara        45  '2020/12/24'    105       132     246.0
25  26     Zara        60  '2020/12/25'    102       126     334.5
26  27    Alice        60      20201226    100       120     250.0
27  28      Bob        60  '2020/12/27'     92       118     241.0
28  29  Charlie        60  '2020/12/28'    103       132       NaN
29  30    Diana        60  '2020/12/29'    100       132     280.0
30  31      Eve        60  '2020/12/30'    102       129     380.3
31  32    Frank        60  '2020/12/31'     92       115     243.0

In [107]:
df=pd.read_json("student-data.json")  # json file
df

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [108]:
df=pd.read_csv('data.csv')   #import dataFrame as csv file
df

    ID     Name  Duration          Date  Pulse  Maxpulse  Calories
0    1    Alice        60  '2020/12/01'    110       130     409.1
1    2      Bob        60  '2020/12/02'    117       145     479.0
2    3  Charlie        60  '2020/12/03'    103       135     340.0
3    4    Diana        45  '2020/12/04'    109       175     282.4
4    5      Eve        45  '2020/12/05'    117       148     406.0
5    6    Frank        60  '2020/12/06'    102       127     300.0
6    7    Grace        60  '2020/12/07'    110       136     374.0
7    8    Henry       450  '2020/12/08'    104       134     253.3
8    9     Iris        30  '2020/12/09'    109       133     195.1
9   10     Jack        60  '2020/12/10'     98       124     269.0
10  11    Karen        60  '2020/12/11'    103       147     329.3
11  12      Leo        60  '2020/12/12'    100       120     250.7
12  13    Megan        60  '2020/12/12'    100       120     250.7
13  14   Nathan        60  '2020/12/13'    106       128     345.3
14  15   Olivia        60  '2020/12/14'    104       132     379.3
15  16     Paul        60  '2020/12/15'     98       123     275.0
16  17    Quinn        60  '2020/12/16'     98       120     215.2
17  18   Rachel        60  '2020/12/17'    100       120     300.0
18  19      Sam        45  '2020/12/18'     90       112       NaN
19  20     Tina        60  '2020/12/19'    103       123     323.0
20  21      Uma        45  '2020/12/20'     97       125     243.0
21  22   Victor        60  '2020/12/21'    108       131     364.2
22  23    Wendy        45           NaN    100       119     282.0
23  24   Xavier        60  '2020/12/23'    130       101     300.0
24  25     Yara        45  '2020/12/24'    105       132     246.0
25  26     Zara        60  '2020/12/25'    102       126     334.5
26  27    Alice        60      20201226    100       120     250.0
27  28      Bob        60  '2020/12/27'     92       118     241.0
28  29  Charlie        60  '2020/12/28'    103       132       NaN
29  30    Diana        60  '2020/12/29'    100       132     280.0
30  31      Eve        60  '2020/12/30'    102       129     380.3
31  32    Frank        60  '2020/12/31'     92       115     243.0

In [109]:
df["Duration"] # single col

0      60
1      60
2      60
3      45
4      45
5      60
6      60
7     450
8      30
9      60
10     60
11     60
12     60
13     60
14     60
15     60
16     60
17     60
18     45
19     60
20     45
21     60
22     45
23     60
24     45
25     60
26     60
27     60
28     60
29     60
30     60
31     60
Name: Duration, dtype: int64

In [110]:
df[["Name",'Pulse']]  #multi col

       Name  Pulse
0     Alice    110
1       Bob    117
2   Charlie    103
3     Diana    109
4       Eve    117
5     Frank    102
6     Grace    110
7     Henry    104
8      Iris    109
9      Jack     98
10    Karen    103
11      Leo    100
12    Megan    100
13   Nathan    106
14   Olivia    104
15     Paul     98
16    Quinn     98
17   Rachel    100
18      Sam     90
19     Tina    103
20      Uma     97
21   Victor    108
22    Wendy    100
23   Xavier    130
24     Yara    105
25     Zara    102
26    Alice    100
27      Bob     92
28  Charlie    103
29    Diana    100
30      Eve    102
31    Frank     92

In [111]:
print(df.loc[1])

ID                     2
Name                 Bob
Duration              60
Date        '2020/12/02'
Pulse                117
Maxpulse             145
Calories           479.0
Name: 1, dtype: object

In [112]:
df=pd.read_csv('data.csv', index_col='ID')  #changing ID as index
df

       Name  Duration          Date  Pulse  Maxpulse  Calories
ID
1     Alice        60  '2020/12/01'    110       130     409.1
2       Bob        60  '2020/12/02'    117       145     479.0
3   Charlie        60  '2020/12/03'    103       135     340.0
4     Diana        45  '2020/12/04'    109       175     282.4
5       Eve        45  '2020/12/05'    117       148     406.0
6     Frank        60  '2020/12/06'    102       127     300.0
7     Grace        60  '2020/12/07'    110       136     374.0
8     Henry       450  '2020/12/08'    104       134     253.3
9      Iris        30  '2020/12/09'    109       133     195.1
10     Jack        60  '2020/12/10'     98       124     269.0
11    Karen        60  '2020/12/11'    103       147     329.3
12      Leo        60  '2020/12/12'    100       120     250.7
13    Megan        60  '2020/12/12'    100       120     250.7
14   Nathan        60  '2020/12/13'    106       128     345.3
15   Olivia        60  '2020/12/14'    104       132     379.3
16     Paul        60  '2020/12/15'     98       123     275.0
17    Quinn        60  '2020/12/16'     98       120     215.2
18   Rachel        60  '2020/12/17'    100       120     300.0
19      Sam        45  '2020/12/18'     90       112       NaN
20     Tina        60  '2020/12/19'    103       123     323.0
21      Uma        45  '2020/12/20'     97       125     243.0
22   Victor        60  '2020/12/21'    108       131     364.2
23    Wendy        45           NaN    100       119     282.0
24   Xavier        60  '2020/12/23'    130       101     300.0
25     Yara        45  '2020/12/24'    105       132     246.0
26     Zara        60  '2020/12/25'    102       126     334.5
27    Alice        60      20201226    100       120     250.0
28      Bob        60  '2020/12/27'     92       118     241.0
29  Charlie        60  '2020/12/28'    103       132       NaN
30    Diana        60  '2020/12/29'    100       132     280.0
31      Eve        60  '2020/12/30'    102       129     380.3
32    Frank        60  '2020/12/31'     92       115     243.0

In [113]:
df.loc[2]

Name                 Bob
Duration              60
Date        '2020/12/02'
Pulse                117
Maxpulse             145
Calories           479.0
Name: 2, dtype: object

In [114]:
print(df.loc[1,['Pulse','Maxpulse']])

Pulse       110
Maxpulse    130
Name: 1, dtype: int64

In [115]:
df=pd.read_json("student-data.json")  # load json
df

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [116]:
filter= df[df["maths"]>80] #filtering data

In [117]:
print(filter)

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [118]:
filter= df[df["gender"]=='Male'] #filtering data

In [119]:
print(filter)

       name gender  physics  maths  english
0      arun   Male       88     87       78
1    rajesh   Male       96    100       95
2   moorthy   Male       89     90       70
3      raja   Male       30     25       40
6    Sundar   Male       12     67       67
8    Dinesh   Male       56     45       67
11      Ram   Male       78     55       47
12  Murugan   Male       34     89       78

In [120]:
filter= df[df["gender"]!='Male'] #filtering data
print(filter)

       name  gender  physics  maths  english
4      usha  Female       67     45       78
5     priya  Female       56     46       78
7   Kavitha  Female       78     71       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
13  Jenifer  Female       67     88       90

In [121]:
filter= df[(df["gender"]!='Male') & (df["maths"]>80)] #filtering data with multiple condition 
print(filter)

       name  gender  physics  maths  english
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
13  Jenifer  Female       67     88       90

In [122]:
print(df.iloc[0:5])

      name  gender  physics  maths  english
0     arun    Male       88     87       78
1   rajesh    Male       96    100       95
2  moorthy    Male       89     90       70
3     raja    Male       30     25       40
4     usha  Female       67     45       78

In [123]:
print(df.iloc[0:5:2, 1:3])

   gender  physics
0    Male       88
2    Male       89
4  Female       67

#### aggregate

In [124]:
print(df.mean(numeric_only='True'))

physics    65.857143
maths      71.285714
english    69.857143
dtype: float64

In [125]:
print(df.median(numeric_only='True'))

physics    69.0
maths      79.0
english    74.0
dtype: float64

In [126]:
print(df.sum(numeric_only='True'))

physics    922
maths      998
english    978
dtype: int64

In [127]:
print(df.min(numeric_only='True'))

physics    12
maths      25
english    23
dtype: int64

In [128]:
print(df.max(numeric_only='True'))

physics    100
maths      100
english    100
dtype: int64

In [129]:
print(df.count(numeric_only='True'))

physics    14
maths      14
english    14
dtype: int64

In [130]:
print(df.mode(numeric_only='True'))

   physics  maths  english
0       56     45     78.0
1       67     90      NaN
2       78    100      NaN

In [131]:
print(df['maths'].mean())

71.28571428571429

In [132]:
group=df.groupby('gender')

In [133]:
print(group)

<pandas.api.typing.DataFrameGroupBy object at 0x000002208584F230>

In [134]:
print(group.mean(numeric_only=True))

          physics      maths    english
gender
Female  73.166667  73.333333  72.666667
Male    60.375000  69.750000  67.750000

In [135]:
print(group['maths'].mean(numeric_only=True))

gender
Female    73.333333
Male      69.750000
Name: maths, dtype: float64

In [159]:
df=pd.read_json("student-data.json")  # load json
df

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [160]:
delete=df.drop(columns=['english'])

In [161]:
delete

       name  gender  physics  maths
0      arun    Male       88     87
1    rajesh    Male       96    100
2   moorthy    Male       89     90
3      raja    Male       30     25
4      usha  Female       67     45
5     priya  Female       56     46
6    Sundar    Male       12     67
7   Kavitha  Female       78     71
8    Dinesh    Male       56     45
9      Hema  Female       71     90
10    Gowri  Female      100    100
11      Ram    Male       78     55
12  Murugan    Male       34     89
13  Jenifer  Female       67     88

In [162]:
df

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [171]:
drop=df.dropna()

In [172]:
drop=df.fillna({'maths':78})

In [173]:
df['name']=df['name'].replace({
    'arun':'arn',
    'Gowri':''
})

In [174]:
df['name']

0         arn
1      rajesh
2     moorthy
3        raja
4        usha
5       priya
6      Sundar
7     Kavitha
8      Dinesh
9        Hema
10
11        Ram
12    Murugan
13    Jenifer
Name: name, dtype: str

In [176]:
duplicate=df['maths'].drop_duplicates()
duplicate

0      87
1     100
2      90
3      25
4      45
5      46
6      67
7      71
11     55
12     89
13     88
Name: maths, dtype: int64

In [178]:
df=pd.read_json("student-data.json")  # load json
df

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [183]:
import pandas as pd

df1 = pd.DataFrame({
    "id": [1, 2, 3],
    "name": ["Arun", "Raj", "Hema"]
})

In [184]:
df2 = pd.DataFrame({
    "id": [1, 2, 3],
    "maths": [90, 85, 95]
})

In [185]:
df = pd.merge(df1, df2)
print(df)

   id  name  maths
0   1  Arun     90
1   2   Raj     85
2   3  Hema     95

In [186]:
pd.merge(df1, df2, on="id", how="inner")

   id  name  maths
0   1  Arun     90
1   2   Raj     85
2   3  Hema     95

In [189]:
df2 = pd.DataFrame({
    "id": [1, 2, 3],
    "maths": [90, 85, 95]
})
import pandas as pd

df1 = pd.DataFrame({
    "id": [1, 2, 3],
    "name": ["Arun", "Raj", "Hema"]
})

In [191]:
pd.merge(df1, df2, on="id", how="right")

   id  name  maths
0   1  Arun     90
1   2   Raj     85
2   3  Hema     95

In [192]:
df["maths_bonus"] = df["maths"].apply(lambda x: x + 5)

In [193]:
df

   id  name  maths  maths_bonus
0   1  Arun     90           95
1   2   Raj     85           90
2   3  Hema     95          100

In [194]:
df["result"] = df["maths"].apply(lambda x: "Pass" if x >= 50 else "Fail")

In [195]:
df

   id  name  maths  maths_bonus result
0   1  Arun     90           95   Pass
1   2   Raj     85           90   Pass
2   3  Hema     95          100   Pass

In [197]:
df["total"] = df.apply(lambda row: row["maths"] + row["maths_bonus"], axis=1)

In [198]:
df

   id  name  maths  maths_bonus result  total
0   1  Arun     90           95   Pass    185
1   2   Raj     85           90   Pass    175
2   3  Hema     95          100   Pass    195

In [199]:
def grade(marks):
    if marks >= 90:
        return "A"
    elif marks >= 75:
        return "B"
    else:
        return "C"

df["grade"] = df["maths"].apply(grade)

In [200]:
df

   id  name  maths  maths_bonus result  total grade
0   1  Arun     90           95   Pass    185     A
1   2   Raj     85           90   Pass    175     B
2   3  Hema     95          100   Pass    195     A

In [205]:
import pandas as pd

students = pd.DataFrame({
    'id':   [1, 2, 3, 4],
    'name': ['Arjun', 'Priya', 'Ravi', 'Meena']
})
scores = pd.DataFrame({
    'id':    [1, 2, 3],
    'score': [85, 92, 78]
})

# Inner — Meena (id=4) is DROPPED, no matching score
df=pd.merge(students, scores, on='id', how='inner')
df

   id   name  score
0   1  Arjun     85
1   2  Priya     92
2   3   Ravi     78

In [206]:
# Left — Meena is KEPT, score becomes NaN
df=pd.merge(students, scores, on='id', how='left')
df

   id   name  score
0   1  Arjun   85.0
1   2  Priya   92.0
2   3   Ravi   78.0
3   4  Meena    NaN